title: DoraHacks Wiki

remote_theme: just-the-docs/just-the-docs

url: https://ylin0504.github.io
baseurl: "/dorahacks"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

just_the_docs:
  search_enabled: true
