title: DoraHacks Wiki

# 用 remote_theme，而不是 theme
remote_theme: just-the-docs/just-the-docs

# 如果是项目页，建议这样配置
url: https://YOUR_GITHUB_USERNAME.github.io
baseurl: "/dorahacks-wiki"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

just_the_docs:
  search_enabled: true
